### ISSUE TITLE
python/pip version

### ISSUE THREAD

**Issue by cfthompson** [ashleygould/aws-shelltools#1]
Might want to consider putting a note in the readme about the version of python/pip required, or at least the version(s) this has been tested on.  There's a lot of old python out there.  I haven't been able to get this set up in python2.7 on Ubuntu 16.04 LTS.  Are you using python3?

**Comment by ashleygould** [comment]
it is supposed to support python 2.7 and 3.4+.  I haven't tried it
on Unbunto.

**Comment by ashleygould** [comment]
dropped support for python 2.7
